version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./node_modules:/node_modules
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./src:/usr/src/app/src
